application: g-apps-sca001
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  script: _go_app

- url: /contacts
  script: _go_app

- url: /contacts/export
  script: _go_app

- url: /contacts/exportxml
  script: _go_app

- url: /contacts/delete
  script: _go_app

- url: /set-action
  script: _go_app

- url: /import
  script: _go_app

- url: /import/do
  script: _go_app

- url: /export
  script: _go_app

- url: /delete
  script: _go_app

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.htm)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.htm)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)
  
- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)
  
# font files
- url: /(.*\.(woff|ttf|eot|svg))
  mime_type: font/opentype
  static_files: static/\1
  upload: static/(.*\.(woff|ttf|eot|svg))
  
# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|pdf))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png|pdf))

# index files
- url: /(.+)/
  static_files: static/\1/index.html
  upload: static/(.+)/index.html
